/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frames;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import source.MarketingEmployee;
import source.Products;
import source.Report;

/**
 *
 * @author Mohamed Yousef
 */
public class MarketingReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form MarketingReport
     */
    public MarketingReport() {
        initComponents();
    }
    
    
    protected void resetPanelData() {
        jTextFieldReportID.setText("");
        jTextFieldProductID.setText("");
        jTextFieldMarketingID.setText("");
        jTextAreaReport.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProductID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMarketingID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldReportID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelSuccessFail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReport = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("Make Report");

        jLabel1.setText("Product ID");

        jLabel3.setText("Your Report :");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Your ID");

        jLabel4.setText("Report ID");

        jTextAreaReport.setColumns(20);
        jTextAreaReport.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldProductID)
                    .addComponent(jTextFieldMarketingID)
                    .addComponent(jTextFieldReportID, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(jLabelSuccessFail)))
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldReportID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabelSuccessFail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMarketingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          if(!jTextFieldMarketingID.getText().equals("") && !jTextFieldProductID.getText().equals("") && !jTextAreaReport.getText().equals("")) {
           
             Report x = new Report();
              Products y = new Products();
             MarketingEmployee z = new MarketingEmployee();
             x.setReportID(Integer.parseInt(jTextFieldReportID.getText()));
              Products pReturned = y.searchProducts(Integer.parseInt(jTextFieldProductID.getText()));
              if(pReturned != null) {
                 x.setProductID(Integer.parseInt(jTextFieldProductID.getText()));
                 try {
                         MarketingEmployee mReturned = z.searchMarketing(Integer.parseInt(jTextFieldMarketingID.getText()));
                        if(mReturned != null) {
                            x.setMarketingID(Integer.parseInt(jTextFieldMarketingID.getText()));
                            x.setReport(jTextAreaReport.getText());
                             if(x.addReport()) {
                                 jLabelSuccessFail.setText("Added Successfully!");
                                 resetPanelData();
                             }
                         else   
                            jLabelSuccessFail.setText("Failed to Insert!");
                 
                        }
                        else 
                            jLabelSuccessFail.setText("Employee Not Found");
                 }
                        
 
                 catch (ParseException ex) {
                     Logger.getLogger(MarketingReport.class.getName()).log(Level.SEVERE, null, ex);
                 }
              }
              
      
              else 
                  jLabelSuccessFail.setText("Product Not Found");
                 
       }
       else 
           jLabelSuccessFail.setText("Missing Required Fields!");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelSuccessFail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaReport;
    private javax.swing.JTextField jTextFieldMarketingID;
    private javax.swing.JTextField jTextFieldProductID;
    private javax.swing.JTextField jTextFieldReportID;
    // End of variables declaration//GEN-END:variables
}
