/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames.Panels;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Mohamed Yousef
 */
import source.*;
public class ProductsList extends javax.swing.JPanel {

    /**
     * Creates new form MarketingList
     */
    public ProductsList() {
        initComponents();
        addRowsTojTable();
        
    }
    
     public Products checkExpiry(ArrayList<Products> x) {
        GregorianCalendar calendar = new GregorianCalendar();
        int month = 1 + calendar.get(GregorianCalendar.MONTH);
        int year = calendar.get(GregorianCalendar.YEAR);
        int i = 0;
        while(i<x.size()) {
        if(month == 12) {
            if(x.get(i).getMonth() == 1)
                if(x.get(i).getYear() -1 == year)
                    return x.get(i); } 
            else if(x.get(i).getYear() == year)
                if(x.get(i).getMonth() + 1 == month)
                     return x.get(i); 
        }
        return null;
    }
     
     public Products checkAmount(ArrayList<Products> x) {
         int i = 0;
         while(i < x.size()) { 
             if(x.get(i).getQuantity() < 20)
                 return x.get(i);
             i++;
         }
         return null;
     }

     public void addRowsTojTable() {
         DefaultTableModel model = (DefaultTableModel) jTable.getModel();
         Object rowData[] = new Object[7];
         Products x = new Products();
         ArrayList<Products> ProductsList = new ArrayList<Products>();
         ProductsList = x.listProducts();
         
         for(Products i : ProductsList) {
             rowData[0] = i.getId();
             rowData[1] = i.getName();
             rowData[2] = i.getDescription();
             rowData[3] = i.getQuantity();
             rowData[4] = i.getPrice();
             rowData[5] = i.getExpiry();
             
             
             if(i.checkExpiry(i))
                 i.deleteProducts(i.getId());
             
             
             
             
             model.addRow(rowData);
         }
         Products p = checkExpiry(ProductsList);
         Products r = checkAmount(ProductsList);
         if(p != null)
              JOptionPane.showMessageDialog(this,"Product " + p.getId() + " is about to expire!","Warning",JOptionPane.WARNING_MESSAGE);
         if(r != null)
             JOptionPane.showMessageDialog(this,"Product " + r.getId() + " is about to be out of stock!","Warning",JOptionPane.WARNING_MESSAGE);
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description", "Quantity", "Price", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
